apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pingpong
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: gcr.io/dictav-net/pingpong:0.0.2
          env:
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-tokens
                  key: pingpong
